#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "vvveb"
name = "Vvveb"
description.en = "CMS to build websites, blogs or ecommerce stores"
description.fr = "CMS pour créer des sites Web, des blogs ou des boutiques de commerce électronique"

version = "1.0.6~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://www.vvveb.com/"
demo = "https://demo.example.com"
admindoc = "https://docs.vvveb.com/installation"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/givanz/Vvveb"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    #[install.path]
    #type = "path"
    #default = "/vvveb"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    url = "https://github.com/givanz/Vvveb/releases/download/1.0.6/latest.zip"
    sha256 = "6a2a5704b060138d52b1487b527b6d5fda0c308fc906cb9e8488219d420c45c0"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-mysqli, php8.3-xml, php8.3-zip, php8.3-dom, php8.3-curl, php8.3-gettext, php8.3-gd"

    [resources.database]
    type = "mysql"
