#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

email=$(ynh_user_get_info --username=$admin --key=mail)

ynh_app_setting_set --key=php_upload_max_filesize --value=256M
ynh_app_setting_set --key=php_post_max_size --value=256M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

#ynh_config_add --template="env.php" --destination="$install_dir/env.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# FINAL BOOKSTACK INSTALL
#=================================================
ynh_script_progression "Install $app"

pushd $install_dir
	php$php_version cli.php install module=index host=127.0.0.1 user=$db_user password=$db_pwd database=$db_name admin[email]=$email admin[password]=$password
popd

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================

### Use these lines only if the app installation needs to be finalized through
### web forms. We generally don't want to ask the final user,
### so we're going to use curl to automatically fill the fields and submit the
### forms.

# Installation with curl
#ynh_script_progression "Finalizing installation..."
#ynh_local_curl "/INSTALL_PATH" "key1=value1" "key2=value2" "key3=value3"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
